### PR TITLE
chore/hyperlink-to-discover-page-on-main-landing-page

### LINKED ISSUE #813: Hyperlinks to Discover pages on Main landing page
### Use Case

Hello, To improve user experience, It would be great if we have an option to configure or It directly comes with clickable hyperlinks out of the box to Discover pages on new main landing page. For example "/discover/events" or "/discover/domains" directly when you click on the Image or stats as shown in the screenshot below. Thanks!
image

### Proposed Solution

_No response_

### Implementation Notes

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out in the [EventCatalog Discord](https://discord.com/invite/3rjaZMmrAm).

### PR DESCRIPTION
**Pull request by carlosallexandre**
Close #813

### CODE REVIEW

**Comment by XaaXaaX** [comment]
@carlosallexandre 
the docker action is on error
you can brings the changes from this PR into your branch if helps https://github.com/event-catalog/eventcatalog/pull/845

**Comment by carlosallexandre** [comment]
Thanks @XaaXaaX. Merge done and passing actions now...

**Comment by carlosallexandre** [comment]
This PR contains changes proposed on #846

**Comment by boyney123** [comment]
Thanks folks, LGTM!

**Pull request merged**
