### PR TITLE
refine and relook rapi-doc openapi renderer

### PR DESCRIPTION
**Pull request by XaaXaaX**
## Motivation
having OpenApi spec viewer with a higher level of look and feel to make it readable but operational.

- [x] Enable Try button
- [x] Enable Auth configuration
- [x] Refine them and styling
- [x] Expand the schema tab by default instead of example
- [x] Set schema representation as tabular

### CODE REVIEW

**Comment by boyney123** [comment]
npm run `npm run format`

**Comment by boyney123** [comment]
Thank you mate, I'm tempted to get this in at the moment, cos it fixed what we have, but also review the other UI too along side it :)

**Comment by boyney123** [comment]
One thing I don't like about spotlight at the moment is this too 
image

**Comment by glc-omid** [comment]
> One thing I don't like about spotlight at the moment is this too 
> image
> 

If you look again here I find redoc very readable personally 
https://redocly.com/redoc

**Pull request merged**
